version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:latest
        auth:
          username: marshallqiu
          password: 5q6w7e8569  # context / project UI env-var reference
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test