version: 2.1
orbs:
  react: thefrontside/react@0.2.0
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
    example-workflow:
      jobs:
        - react/test
